Repository wecode-bootcamp-korea/10-Weplash-frontend, pull requests merged in 2020-08, with the labels that each got.

#3 Add: TopicInfo & Card Component Layout
  package-lock.json
  public/Data/card.json
  public/Data/data.js
  public/Data/data.json
  public/Images/Unsplash_Symbol.png
  public/Images/img
  public/index.html
  src/Component/Card/Card.js
  src/Component/Card/CardList.js
  src/Component/Card/CardTopBtns.js
  src/Component/Card/CardUser.js
  src/Component/TopicInfo.js
  src/Pages/Topic/Topic.js
  src/Styles/StyleTheme.js
  src/config.js
Labels: Status: 리뷰 요청

#5 Add: UserCard Layout (mouse event)
  public/Data/user.json
  src/Component/Card/CardTopBtns.js
  src/Component/Card/CardUser.js
  src/Component/TopicInfo.js
  src/Component/UserCard/UserCard.js
  src/config.js
Labels: Status: Accepted

#4 Add: 로그인 & 회원가입 Layout
  package-lock.json
  package.json
  public/Images/googleLogo.jpg
  public/index.html
  src/Pages/Login/Login.js
  src/Pages/SignUp/SignUp.js
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#7 Refactor: API 연결 및 Pagination 적용
  public/Data/card.json
  src/Component/Card/Card.js
  src/Component/Card/CardList.js
  src/Component/Card/CardTopBtns.js
  src/Component/Card/CardUser.js
  src/Component/Loading.js
  src/Component/TopicInfo.js
  src/Component/UserCard/UserCard.js
  src/Routes.js
  src/config.js
  src/icons.js
Labels: Status: Accepted

#1 Add: Nav 초기 레이아웃
  src/Component/Nav.js
  src/Component/Nav/CategoriesNav.js
  src/Component/Nav/HeaderNav.js
  src/Component/Nav/Nav.js
  src/Component/Nav/navData.js
  src/Routes.js
  src/Svg/svg.js
Labels: Status: Accepted

#10 Refactor: Replace hover with onMouse event
  package-lock.json
  src/Component/Card/Card.js
  src/Component/Card/CardList.js
  src/Component/Card/CardTopBtns.js
  src/Component/Collection/CollectionModal.js
  src/Component/Loading.js
  src/Component/UserCard/UserCard.js
  src/config.js
Labels: Status: 리뷰 요청

#8 Add: Photo 상세 모달 창 구현
  public/Data/cardData.json
  public/Data/tempCardData.json
  public/index.html
  src/Component/Card/Card.js
  src/Component/Card/CardList.js
  src/Component/Card/CardTopBtns.js
  src/Component/Card/CardUser.js
  src/Component/Collection/Collection.js
  src/Component/Collection/CollectionModal.js
  src/Component/Dimmer.js
  src/Component/Modal/Buttons/AddIcon.js
  src/Component/Modal/Buttons/BtnClose.js
  src/Component/Modal/Buttons/BtnDirection.js
  src/Component/Modal/Buttons/Buttons.js
  src/Component/Modal/Buttons/DownloadIcon.js
  src/Component/Modal/Buttons/HashTag.js
  src/Component/Modal/Buttons/HeartIcon.js
  src/Component/Modal/Buttons/InfoIcon.js
  src/Component/Modal/Buttons/ShareIcon.js
  src/Component/Modal/Dimmer.js
  src/Component/Modal/Modal.js
  src/Component/Modal/ModalContents/ModalContents.js
  src/Component/Modal/ModalContents/RelatedContents/RelatedCollections.js
  src/Component/Modal/ModalContents/RelatedContents/RelatedContents.js
  src/Component/Modal/ModalContents/RelatedContents/RelatedPhotos.js
  src/Component/Modal/ModalContents/RelatedContents/RelatedTags.js
  src/Component/Modal/ModalPage.js
  src/Component/Nav/CategoriesNav.js
  src/Component/Nav/HeaderNav.js
  src/Pages/Main/Main.js
  src/Pages/Main/TempCard.js
  src/Pages/Topic/Card.js
  src/Pages/Topic/Topic.js
  src/Routes.js
  src/api.js
Labels: Status: 리뷰 요청

#6 Add: UserPage 레이아웃 완성
  public/Data/userData.json
  src/Pages/UserPage/Components/Collections.js
  src/Pages/UserPage/Components/FooterIcon.js
  src/Pages/UserPage/Components/Likes.js
  src/Pages/UserPage/Components/MyProfile.js
  src/Pages/UserPage/Components/Photos.js
  src/Pages/UserPage/Components/UserProfile.js
  src/Pages/UserPage/UserPage.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#13 Add: 이미지 업로드 기능 레이아웃 및 기능 구현 완성
  public/Images/upload_success.png
  src/Component/Modal/Dimmer.js
  src/Component/Nav/HeaderNav.js
  src/Component/Nav/Nav.js
  src/Component/Upload/LoadedImage.js
  src/Component/Upload/LoadingImage.js
  src/Component/Upload/Upload.js
  src/Component/Upload/UploadFooter.js
  src/Component/Upload/UploadModal.js
  src/icons.js
Labels: Status: Accepted

#9 Add : 메인 서치박스 레이아웃 완성
  package-lock.json
  public/index.html
  src/Component/Card/CardUser.js
  src/Component/Nav/HeaderNav.js
  src/Component/TopicInfo.js
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/Main/MainPage.js
  src/Pages/Main/MainSearch.js
  src/Pages/SignUp/SignUp.js
  src/Pages/UserPage/UserPage.js
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#11 Add : Search Page 레이아웃 완성
  package-lock.json
  package.json
  public/Images/arrow.png
  public/Images/arrow.svg
  src/Component/Card/Card.js
  src/Component/Card/CardList.js
  src/Component/Search/FilterNav.js
  src/Component/Search/SearchText.js
  src/Pages/SearchPage/SearchPage.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#12 Add: CollectionModal 추가 (Conflict 해결)
  public/Data/cardData.json
  public/Data/data.json
  public/Data/tempCardData.json
  public/Data/user.json
  src/Component/Card/Card.js
  src/Component/Card/CardList.js
  src/Component/Card/CardTopBtns.js
  src/Component/Card/CardUser.js
  src/Component/Collection/AddCollection.js
  src/Component/Collection/CollectionCards.js
  src/Component/Collection/CollectionModal.js
  src/Component/Collection/CreateModal.js
  src/Component/Dimmer.js
  src/Component/Nav/Nav.js
  src/Component/TopicInfo.js
  src/Component/UserCard/UserCard.js
  src/Pages/Topic/Card.js
  src/Pages/Topic/Topic.js
  src/Routes.js
  src/config.js
  src/icons.js
Labels: Status: 리뷰 요청

#14 Add: Nav 경로 수정 및 로그인 상태 Redux적용
  package-lock.json
  package.json
  src/Component/Modal/Modal.js
  src/Component/Nav/CategoriesNav.js
  src/Component/Nav/HeaderNav.js
  src/Component/Nav/Nav.js
  src/Component/Nav/NavUiBeforeLogin.js
  src/Component/Nav/NavUiLogin.js
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/Main/MainSearch.js
  src/Routes.js
  src/api.js
  src/config.js
  src/index.js
  src/redux/actions/index.js
  src/redux/reducers/auth.js
  src/redux/reducers/index.js
Labels: Status: 리뷰 요청

#16 Add: following 기능 구현 (Review 반영)
  public/index.html
  src/Component/Card/CardList.js
  src/Component/Card/CardTopBtns.js
  src/Component/Card/CardUser.js
  src/Component/Collection/AddCollection.js
  src/Component/Collection/CollectionModal.js
  src/Component/Loading.js
  src/Component/Upload/UploadModal.js
  src/Component/UserCard/UserCard.js
  src/Pages/Following.js
  src/Pages/Login/Login.js
  src/Pages/Main/MainPage.js
  src/Pages/Topic/Topic.js
  src/Routes.js
  src/api.js
  src/config.js
Labels: Status: Accepted, Status: 리뷰 요청
